


@startuml Matrix_Project
skinparam ClassAttributeIconSize 0 
skinparam Linetype ortho

Class Matrix{
- int aantalRijen
- int aantalKolommen 
+ int [][] matrix {readOnly}


+ Matrix(dubelleArray: int [][])
+ Matrix()
+ drawMatrix(element: Table-Tag) : void
+ vermenigvuldigMatrix(matrix_2: Matrix): Matrix
+ getDeterminant(): int
+ getInverse(): Matrix
+ getTransponneerde(): Matrix

}

abstract Class Tutorial{
- string [] Beschrijving
- int stapNummer


+ refresh(stapnummer : int): void
+ Tutorial(matrix Matrix)


} 


Class VermenigvuldigTutorial{

+ VermenigvuldigTutorial(matrix_1 : Matrix, matrix_2 : Matrix)

}

Class TransponneerTutorial{

+ TransponneerTutorial(matrix : Matrix)
}

Class InverseTutorial{
+ InverseTutorial(matrix : Matrix)
}

Class DeterminantTutorial{
+ DeterminantTutorial(matrix : Matrix)
}


abstract Class Oefeningen{
    - Matrix[] OefeningenReeks


    + Oefeningen(aantalOefeningen: int)    
    + showHint(element: HTML-Tag ): void
    + correct(): boolean
    
}

Class VermenigvuldigingOefening{
    +VermenigvuldigingOefening(aantalOefeningen: int)
    +correct: boolean
}

Class DeterminantOefening{
    +DeterminantOefening(aantalOefeningen : int)
    +correct: boolean 
}
Class InverseOefening{
    +InverseOefening(aantalOefeningen: int)
    +correct: boolean
}

Tutorial <|-- VermenigvuldigTutorial
Tutorial <|-- DeterminantTutorial
Tutorial <|-- InverseTutorial
Tutorial <|-- TransponneerTutorial

Oefeningen <|-- VermenigvuldigingOefening
Oefeningen <|-- DeterminantOefening
Oefeningen <|-- InverseOefening

Matrix "*" -o Oefeningen  
Tutorial o- "*" Matrix









@enduml