


@startuml Matrix_Project
skinparam ClassAttributeIconSize 0 


class Matrix{
    + int aantalRijen
    + int aantalKolommen
    + int [][] matrix
    __
    + Matrix(aantalRijen: int=3, aantalKolommen: int=3, fill: String=null)
    ..
    + copyMatrix(): Matrix
    + vermenigvuldigMatrix(matrix_2: Matrix): Matrix
    + importMatrix(dubbele_array: [][]): [][]
    + drawMatrix(element: Table-Tag, hoofd: String=null): void
    + getTransponneerde(): Matrix
    + getCofactor(mat: [][], p: int, q: int, n: int): [][]
    + getDeterminant(mat: [][]=this.matrix, n: int=this.aantalRijen): int
    + adjunct(A: [][]=this.matrix, n: int=this.aantalRijen): Matrix
    + getInverse(A: [][]=this.matrix, n: int=this.aantalRijen): {determinant: int, adjunct: Matrix, inverse: Matrix} of false
    + toString(): String
}

class TutorialPage{
    + Map<name: String, description: String, uitlegb: String> alle_beschrijvingen
    - Map<naam: String, tutorials: Tutorial[]> tutorials
    - Tutorial tutorial
    - HTML-Tag tabel1
    - HTML-Tag tabel2
    - HTML-Tag tabel3
    - HTML-Tag[] tabellen
    - int tutorialnummer
    __
    + constructor()
    ..
    + startTutorial(naam: String, index: int): void
    + updateBeschrijving(tekst: String): void
    + endTutorial(): void
    + nextTutorial():void
    + changeStep(): void
}

class OefeningPage{
    + String[] alle_oefeningen
    + Map<name: String, description: String> alle_beschrijvingen
    - Map<naam: String, oefeningen: Oefening[]> oefeningen
    - Oefeningen oefening
    - int oefeningindex
    - String naam
    - HTML-Tag tabel1
    - HTML-Tag tabel2
    - HTML-Tag tabel3
    - HTML-Tag[] tabellen
    __
    + constructor()
    ..
    + startOefening(naam: String): void
    + checkOefening(): boolean
    + nextOefening(): void
    + eindeOefening(): void
}


abstract class Tutorial{
    - int stapNummer
    - int antal_matrices
    - Matrix matrix1
    - Matrix data
    - finished
    - int rij1
    - int kolom1
    - Matrix[] matrices
    __
    + Tutorial(m1: Matrix)
    ..
    + refresh(stapnummer: int): Error
    + drawMatrices(): void
}

class VermenigvuldigTutorial{
    - int kolom2
    - int som
    - String tekst
    - String uitleg
    - Matrix matrix2
    __
    + VermenigvuldigTutorial(m1: Matrix, m2: Matrix)
    ..
    + drawMatrices(): void
    + refresh(tutorialPage: TutorialPage): {finished: boolean, data: map<mat: Matrix, hoofding: String>, tekst: String}
}

class TransponneerTutorial{
    __
    + TransponneerTutorial(m1: Matrix)
    ..
    + refresh(tutorialpage: TutorialPage): {finished: boolean, data: map<mat: Matrix, hoofding: String>, tekst: String}
}

class DeterminantTutorial{
    - String tekst
    - String determinant
    __
    + DeterminantTutorial(m1: Matrix)
    ..
    + addDiv(element: HTML-Tag, classe: HTML-class): void
    + refresh(tutorialpage: TutorialPage): {finished: boolean, data: map<mat: Matrix, hoofding: String>, tekst: String}
}

class InverseTutorial{
    - String tekst
    - Matrix matrix2
    - Matrix matrix3
    - [] gr
    - [] gk
    - int det
    __
    + InverseTutorial(m1: Matrix)
    ..
    + addDiv(element: HTML-Tag, classe: HTML-class): void
    + refresh(tutorialpage: TutorialPage): {finished: boolean, data: map<mat: Matrix, hoofding: String>, tekst: String}
}


abstract class Oefeningen{
    - Matrix matrix1
    - int aantal_matrices
    - Matrix data
    - boolean finished
    - Matrix[] matrices
    __
    + Oefeningen(m1: Matrix)
    ..
    + maakInvul(): Error
    + checkOplossing(): Error
    + setHint(tekst: String): void
}

class VermenigvuldigOefening{
    - Matrix oplossing
    - Matrix matrix2
    __
    + VermenigvuldigOefening(m1: Matrix, m2: Matrix)
    ..
    + getMatrix(): Matrix
    + correct(invul: Matrix): boolean
    + checkOplossing(object: VermenigvuldigOefening): boolean
    + changeInvul(): void
    + maakInvul(): void
}

class DeterminantOefening{
    - int oplossing
    __
    + DeterminantOefening(m1: Matrix)
    ..
    + getOplossing(): int
    + checkOplossing(object: DeterminantOefening): boolean
    + maakInvul(): void
    + fout1(): int
    + fout2(): int
}

class InverseOefening{
    - Matrix oplossing
    __
    + InverseOefening(m1: Matrix, strikvraag: boolean)
    ..
    + getOplossing(): String
    + checkOplossing(object: InverseOefening): boolean
    + maakInvul(): void
    + fout1(): Matrix
    + fout2(): Matrix
}


class Speler{
    - String naam
    - Map<String, boolean> tutorials_finished
    __
    + Speler(naam: String)
    ..
    + getData(): Map<String, boolean>
    + eindTutorialOefening(naamTutOef: String): void
    + saveData(): void
}



Oefeningen <|-- VermenigvuldigOefening
Oefeningen <|-- DeterminantOefening
Oefeningen <|-- InverseOefening

Matrix "*" -o Oefeningen
Tutorial o- "*" Matrix

TutorialPage  o- Tutorial
Oefeningen -o OefeningPage

Tutorial <|-- VermenigvuldigTutorial
Tutorial <|-- DeterminantTutorial
Tutorial <|-- InverseTutorial
Tutorial <|-- TransponneerTutorial

Speler --> TutorialPage
Speler --> OefeningPage
@enduml