@startuml
autonumber

actor Gebruiker
participant MainProgram
participant OefeningPage
participant Oefeningen
participant VermenigvuldigOefening
participant Matrix
participant Speler
participant localStorage


activate MainProgram
activate Matrix
activate Speler
activate localStorage


== Oefeningen ==
Gebruiker -> MainProgram: klik op een oefening of via tutorial
MainProgram -> OefeningPage: Open OefeningPage
deactivate MainProgram
activate OefeningPage


OefeningPage -> OefeningPage: init()
OefeningPage -> OefeningPage: new OefeningPage()

OefeningPage -> localStorage: getItem("selected_button")
    localStorage -->> OefeningPage: naam deelsysteem

OefeningPage -> OefeningPage: startOefening(naam deelsysteem)
opt if deelsysteem is VermenigvuldigOefening
    OefeningPage -> Matrix: new Matrix(3, 3)
    OefeningPage -> Matrix: new Matrix(3, 3)

    OefeningPage -> VermenigvuldigOefening: new VermenigvuldigOefening(Matrix1, Matrix2)
        activate VermenigvuldigOefening
        VermenigvuldigOefening -> Oefeningen: constructor()
            activate Oefeningen
            Oefeningen -->> VermenigvuldigOefening: constructor
        VermenigvuldigOefening -> Matrix: vermenigvuldigMatrix(.)

    OefeningPage -> VermenigvuldigOefening: maakInvul()
        VermenigvuldigOefening -> VermenigvuldigOefening: changeInvul()
        VermenigvuldigOefening -> Oefeningen: setHint(.)

    loop foreach oefening.matrices[i]
        OefeningPage -> VermenigvuldigOefening: matrices[i]
            VermenigvuldigOefening -> Oefeningen: matrices[i]
                Oefeningen -->> VermenigvuldigOefening: matrices[i]
            VermenigvuldigOefening -->> OefeningPage: matrices[i]

        OefeningPage -> Matrix: drawMatrix(.)
    end

    opt check
       Gebruiker -> OefeningPage: klikt op Check
       OefeningPage ->  VermenigvuldigOefening: checkOplossing(.)
           VermenigvuldigOefening -> VermenigvuldigOefening: getMatrix()
               VermenigvuldigOefening -> Matrix: new Matrix(.,.)
           VermenigvuldigOefening -> VermenigvuldigOefening: correct(.)
               opt als juist
                        VermenigvuldigOefening -> Gebruiker: alert("goed")
                    else als fout
                        VermenigvuldigOefening -> Gebruiker: alert("slecht")
               end
    end

    opt exit
       Gebruiker -> OefeningPage: klik op exit
       OefeningPage -> OefeningPage: terug()
           OefeningPage -> localStorage: getItem("huidige speler")
               localStorage -->> OefeningPage: huidige speler

           OefeningPage -> Speler: new Speler(spelernaam)
               Speler -> localStorage: getItem(naam)
                   localStorage -->> Speler: data over speler
               Speler -> localStorage: setItem("huidige speler", naam)

           OefeningPage -> localStorage: getItem("selected_button")
               localStorage -->> OefeningPage: naam deelsysteem

           OefeningPage -> Speler: eindTutorialOefening(naam deelsysteem)
               Speler -> Speler: saveData()
                   Speler -> localStorage: setItem(naam, data)

           OefeningPage -> MainProgram: open Main (Sequentiediagram_startup)
           deactivate OefeningPage
           deactivate Oefeningen
           deactivate VermenigvuldigOefening
           activate MainProgram
    end
end


@enduml