@startuml
autonumber

actor Gebruiker
participant MainProgram
participant TutorialPage
participant Tutorial
participant VermenigvuldigTutorial
participant OefeningPage
participant Oefeningen
participant VermenigvuldigOefening
participant Matrix
participant Speler
participant localStorage




== Startup Program ==

Gebruiker ->  MainProgram: Open Main
activate MainProgram

MainProgram -> MainProgram: init()



== Speler Maken ==

MainProgram -> MainProgram: spelerMaken()

MainProgram -> Gebruiker: prompt(naam?)
Gebruiker -->> MainProgram: naam

MainProgram -> Speler: Speler(naam)
activate Speler

Speler -> localStorage: getItem(naam)
activate localStorage
localStorage -->> Speler: data over speler
Speler -> Speler: saveData()
Speler -> localStorage: setItem(naam, data)
Speler -> localStorage: setItem("huidige speler", naam)

MainProgram -> Speler: getData()
Speler -->> MainProgram: Map<String,boolean>



== HTML goed genereren ==

MainProgram -> MainProgram: haalKnoppen()

MainProgram -> TutorialPage: TutorialPage.alle_beschrijvingen
activate TutorialPage
TutorialPage-->>MainProgram: returns alle_beschrijvingen

MainProgram -> OefeningPage: OefeningPage.alle_oefeningen
activate OefeningPage
OefeningPage-->>MainProgram: returns alle_oefeningen

MainProgram -->> MainProgram: generate html page



== Kies Deelsysteem ==

Gebruiker -> MainProgram: Kiest Deelsysteem

MainProgram -> MainProgram: ListenToKnop(event)
MainProgram -> localStorage: setItem("selected_button", naam deelsysteem)


opt  if deelsysteem is een Tutorial
        MainProgram -> TutorialPage: open TutorialPage
        TutorialPage -->> TutorialPage: generate html page (stap 27)
    
     else if deelsysteem is een Oefening
        MainProgram -> OefeningPage: open OefeningPage
        OefeningPage -->> OefeningPage: generate html page (stap 88)

end
deactivate MainProgram



== Tutorials  ==
deactivate OefeningPage

TutorialPage -> TutorialPage: init()

TutorialPage -> localStorage: getItem("selected_button")
localStorage -->> TutorialPage: naam deelsysteem

TutorialPage -> TutorialPage: startTutorial(naam deelsysteem, 0)

opt  if deelsysteem is VermenigvuldigTutorial

        loop subtutorial


            TutorialPage -> Matrix: new Matrix(3, 3, true)
            activate Matrix
            TutorialPage -> Matrix: new Matrix(3, 3, true)

            TutorialPage -> VermenigvuldigTutorial: new VermenigvuldigTutorial(Matrix1, Matrix2)
            activate VermenigvuldigTutorial

            VermenigvuldigTutorial -> Tutorial: constructor()
            activate Tutorial
            Tutorial -->> VermenigvuldigTutorial: constructor

            VermenigvuldigTutorial -> Matrix: new Matrix(.,.,"0")


    '        TutorialPage -> Matrix: new Matrix(2, 2)
    '        TutorialPage -> Matrix: new Matrix(2, 4)
    '
    '        Matrix -->> TutorialPage: Matrix3
    '        Matrix -->> TutorialPage: Matrix4
    '
    '        TutorialPage -> VermenigvuldigTutorial: new VermenigvuldigTutorial(Matrix3, Matrix4)
    '        VermenigvuldigTutorial -> Tutorial: constructor()
    '        Tutorial -->> VermenigvuldigTutorial: constructor
    '
    '        VermenigvuldigTutorial -> Matrix: new Matrix(.,.,"0")
    '        Matrix -->> VermenigvuldigTutorial: "0" Matrix

            loop foreach tutorial.matrices[i]
                    TutorialPage -> VermenigvuldigTutorial: matrices[i]
                    VermenigvuldigTutorial -> Tutorial: matrices[i]
                    Tutorial -->> VermenigvuldigTutorial: matrices[i]
                    VermenigvuldigTutorial -->> TutorialPage: matrices[i]

                    TutorialPage -> Matrix: drawMatrix(.)

            end

            TutorialPage -> TutorialPage: showDescription()
            TutorialPage -> localStorage: getItem("selected_button")
            localStorage -->> TutorialPage: naam deelsysteem
            TutorialPage -> localStorage: getItem("selected_button")
            localStorage -->> TutorialPage: naam deelsysteem

            loop while niet laatste stap
                opt nextStep
                    Gebruiker -> TutorialPage: klik op next

                    TutorialPage -> TutorialPage: ListenToKnop(event)
                    TutorialPage -> TutorialPage: changeStep()

                    TutorialPage -> VermenigvuldigTutorial: refresh(tutorialPage)
                    VermenigvuldigTutorial -->> TutorialPage: {finished:., data:., tekst:.}

                    TutorialPage -> Matrix: drawMatrix(.)
                    TutorialPage -> TutorialPage: updateBeschrijving(.)

                end
                opt exit
                   Gebruiker -> TutorialPage: klik op exit

                   TutorialPage -> TutorialPage: terug()

                   TutorialPage -> localStorage: getItem("huidige speler")
                   localStorage -->> TutorialPage: huidige speler

                   TutorialPage -> Speler: new Speler(spelernaam)

                   Speler -> localStorage: getItem(naam)
                   localStorage -->> Speler: data over speler
                   Speler -> localStorage: setItem("huidige speler", naam)

                   TutorialPage -> localStorage: getItem("selected_button")
                   localStorage -->> TutorialPage: naam deelsysteem

                   TutorialPage -> Speler: eindTutorialOefening(naam deelsysteem)
                   Speler -> Speler: saveData()
                   Speler -> localStorage: setItem(naam, data)

                   TutorialPage -> MainProgram: open Main (stap 2)
                   activate MainProgram
                   deactivate MainProgram

                end
            end

            TutorialPage -> localStorage: getItem("selected_button")
            localStorage -->> TutorialPage: naam deelsysteem

            TutorialPage -> TutorialPage: nextTutorial()

        end

        TutorialPage -> TutorialPage: endTutorial()

        TutorialPage -> localStorage: getItem("selected_button")
        localStorage -->> TutorialPage: naam deelsysteem

        TutorialPage -> localStorage: getItem("huidige speler")
        localStorage -->> TutorialPage: huidige speler

        TutorialPage -> Speler: new Speler(spelernaam)

        Speler -> localStorage: getItem(naam)
        localStorage -->> Speler: data over speler
        Speler -> localStorage: setItem("huidige speler", naam)

        TutorialPage -> localStorage: getItem("selected_button")
        localStorage -->> TutorialPage: naam deelsysteem

        TutorialPage -> Speler: eindTutorialOefening(naam deelsysteem)
        Speler -> Speler: saveData()
        Speler -> localStorage: setItem(naam, data)

end


' nog niet gemaakt
== Koppeling naar andere pagina ==


opt gebruiker pressed oefening button
    TutorialPage->OefeningPage: open OefeningPage (stap 88)
    activate OefeningPage
   else  gebruiker pressed main button
   TutorialPage->MainProgram: open Main (stap 2)
 activate MainProgram
end
TutorialPage->Speler:eindTutorialOefening(Tutorial naam)
deactivate MainProgram
deactivate TutorialPage
deactivate Tutorial







== Oefeningen ==

OefeningPage -> OefeningPage: init()
OefeningPage -> OefeningPage: new OefeningPage()

OefeningPage -> localStorage: getItem("selected_button")
localStorage -->> OefeningPage: naam deelsysteem

OefeningPage -> OefeningPage: startOefening(naam deelsysteem)
opt if deelsysteem is VermenigvuldigOefening
    OefeningPage -> Matrix: new Matrix(3, 3, true)
    OefeningPage -> Matrix: new Matrix(3, 3, true)

    OefeningPage -> VermenigvuldigOefening: new VermenigvuldigOefening(Matrix1, Matrix2)
    activate VermenigvuldigOefening

    VermenigvuldigOefening -> Oefeningen: constructor()
    activate Oefeningen
    Oefeningen -->> VermenigvuldigOefening: constructor

    VermenigvuldigOefening -> Matrix: new Matrix(.,.,"0")
    VermenigvuldigOefening -> Matrix: vermenigvuldigMatrix(.)

    OefeningPage -> VermenigvuldigOefening: maakInvul()
    loop foreach oefening.matrices[i]
        OefeningPage -> VermenigvuldigOefening: matrices[i]
        VermenigvuldigOefening -> Oefeningen: matrices[i]
        Oefeningen -->> VermenigvuldigOefening: matrices[i]
        VermenigvuldigOefening -->> OefeningPage: matrices[i]

        OefeningPage -> Matrix: drawMatrix(.)

    end

    opt check
       Gebruiker -> OefeningPage: klikt op Check
       OefeningPage ->  VermenigvuldigOefening: checkOplossing(.)

       VermenigvuldigOefening -> VermenigvuldigOefening: getMatrix()
       VermenigvuldigOefening -> VermenigvuldigOefening: correct(.)
       opt als juist
            VermenigvuldigOefening -> Gebruiker: alert("goed")
            else als fout
            VermenigvuldigOefening -> Gebruiker: alert("slecht")

       end

    end
    opt exit
       Gebruiker -> OefeningPage: klik op exit

       OefeningPage -> OefeningPage: terug()

       OefeningPage -> localStorage: getItem("huidige speler")
       localStorage -->> OefeningPage: huidige speler

       OefeningPage -> Speler: new Speler(spelernaam)

       Speler -> localStorage: getItem(naam)
       localStorage -->> Speler: data over speler
       Speler -> localStorage: setItem("huidige speler", naam)

       OefeningPage -> localStorage: getItem("selected_button")
       localStorage -->> OefeningPage: naam deelsysteem

       OefeningPage -> Speler: eindTutorialOefening(naam deelsysteem)
       Speler -> Speler: saveData()
       Speler -> localStorage: setItem(naam, data)

       OefeningPage -> MainProgram: open Main (stap 2)
       activate MainProgram
       deactivate MainProgram

    end




end



' Nog niet gemmakt
== Koppeling naar andere pagina ==


opt gebruiker pressed Tutorial button
    TutorialPage<-OefeningPage:target button
    activate TutorialPage
   else  gebruiker pressed main button
   OefeningPage->MainProgram
 activate MainProgram
end

OefeningPage->Speler:eindTutorialOefening(Oefening naam)



==einde programma==

deactivate MainProgram
deactivate TutorialPage
deactivate Tutorial
deactivate VermenigvuldigTutorial
deactivate OefeningPage
deactivate Oefeningen
deactivate VermenigvuldigOefening
deactivate Matrix
deactivate Speler
deactivate localStorage
@enduml

